### ISSUE TITLE
Gatsby Plugin indexing

### ISSUE THREAD

**Issue by RobinCsl** [Jedidiah/gatsby-source-soundcloud#3]
Hello again 👋

Similar to the other source plugin for Twitch, this one would also benefit from a patch version being released to NPM so that the `gatsby-plugin` keyword features there too.

cf. https://github.com/Jedidiah/gatsby-source-twitch/issues/2

This is part of https://github.com/gatsbyjs/gatsby/issues/14013

Thanks a lot!

**Comment by Jedidiah** [comment]
Thanks @RobinCsl, have published 2.0.5 to NPM.

**Comment by RobinCsl** [comment]
Great, @Jedidiah! Thanks!!
